import turtle
window = turtle.Screen()
turtle.bgcolor('WHITE')
turtle.title('main page')

pointer = turtle.Turtle()
pointer.color('black')
pointer.forward(100)
pointer.left(120)
pointer.forward(100)
pointer.left(120)
pointer.forward(100)
pointer.penup()
pointer.right(120)
pointer.forward(50)
pointer.right(120)
pointer.pendown()
pointer.forward(130)
pointer.right(120)
pointer.forward(120)
pointer.right(115)
pointer.forward(130)
turtle.done()
